DROP DATABASE IF EXISTS php_demo1;
CREATE DATABASE php_demo1;

USE php_demo1;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL
);
